### PR TITLE
Task completed

### PR DESCRIPTION
**Pull request by ManojSreekumarK**
Reviewer: Anna Ricci Benson @pank-j

### CODE REVIEW

**Comment by ManojSreekumarK** [comment]
Task completed

**Comment by pank-j** [comment]
What is this PR for?

**Comment by ManojSreekumarK** [comment]
> What is this PR for?

We were instructed by Anna ma'am to add our code as branches to this repo but since we didn't have write access to this repo we forked and made a pr.  We hoped that if u approve it we can make a push request.

**Comment by pank-j** [comment]
Forking is fine. But you should raise a PR to your own repo's (the forked one) main branch and not this repo. https://github.com/ManojSreekumarK/frontons-fe-training/compare/main...ManojSreekumarK:frontons-fe-training:ManojPIT1831

**Pull request closed without merging**
